package main

type AutoGenerated struct {
	GlobalEnbId struct {
		Mcc   int
		Mnc   int
		Enbid int
	}
	SupportedTAList []struct {
		TAC           int
		BroadCastPLMN []struct {
			MCC                int
			MNC                int
			B                  []string
			SupportedSliceList []struct {
				SST int
				SD  int
			}
		}
	}
	PagingDRx string
}
